### ISSUE TITLE
Defining a proc/func sharing a built-in proc/func's name does not show meaningful error message

### ISSUE THREAD

**Issue by aitorres** [joseluisjb1990/gacela#13]
If the user tries to define a procedure (or a function) whose name is already used by one of Graciela's _built-in_ procedures/functions, the compiler will instead state that no identifier was given. This error can be made more helpful.

For example, if I try to run the following program:

```
program Procname begin

proc random() 
{pre true pre}
{post true post}
|[
	skip
]|

main 
|[
	random(); 
]|
end
```

This is the output:

```
aitorres@fibonacci:~/programas/Graciela$ rungraciela Procname.gcl 
procname.gcl:3:6: Error:
	An identifier was expected but none was given.
```

Of course, an identifier _was_ given, it just happens to be one that is already used by Graciela. The output is the same if, instead of a procedure, you try to define a function like that. I found about this when I tried to make a random number generator, not knowing that Graciela already has a random function/procedure (although I don't know how to make it work, now I know it exists). This happens for other words, such as if tried to make a procedure called _max_ or _min_.

Now: I know that, if I try to define two procedures with the same name, the compiler will show the following error: _Redefinition of procedure `name`._ (where _name_ is the name of the procedure defined two or more times), which is at least more useful. Maybe this message can also be shown when someone tries to define a procedure using a reserved name, or  you can implement a more specific, particular error message.

In case you need the information, I tried this on Xubuntu 17.04, 64 bits, running Graciela 2.0.4.0 (having manually installed Clang 3.5).

**Comment by adgalad** [comment]
Thanks for noticed that. I fixed the errors given by the compiler and will be added in the next update.

Since the very beginning of the project, Graciela's native procedures were not  "functions" per se but reserved words. So the compiler couldn't verify a redefinition of `random` or `read` the same way as it verifies a redefinition of a user's procedure/function. I don't know the reasons behind this decision in the original project, but maybe because some native procedures need special syntax.
For instance, to read from a file using you need the reserved word `from`:
```
main 
|[
        var x : int;
	read(x) from "/home/user/archive.txt"
]|
```

Random procedure is used by giving a variable of type `int`, `char`, `boolean`or `float`.
``` 
var c : char; 
var f : float; 
random(x);
random(f)
```
